swagger: '2.0'
info:
  title: Wine Regression API
  version: "0.1"
  description: An API that can predict wine's price

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: wine_regression_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: wine_regression_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: points
          required: true
          description: The points of the wine
          type: number
      responses:
        '200':
          description: Regression performed successfully
        '500':
          description: Unable to perform the Regression
