swagger: '2.0'
info:
  title: Wine Classification Description API
  version: "0.1"
  description: An API that can predict wine's grade ()

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: wine_classification_description_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: wine_classification_description_api.clf_predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: description
          required: true
          description: The price of the wine
          type: string
      responses:
        '200':
          description: Classification performed successfully
        '500':
          description: Unable to perform the Classification
